AWSTemplateFormatVersion: "2010-09-09"
Description: IAMPolicy and IAMRole to allow read write access to DynamoDB
Parameters:
  ClusterName: 
    Description: EKS cluster name
    Type: String
  Namespace:
    Description: EKS cluster namespace to create service account in.
    Type: String
  Name:
    Description: EKS cluster create service account name.
    Type: String
  Ec2IAMPolicyJson:
    Type: String
    Description: IAM policy json string with specified resources and json
  ElbIAMPolicyJson:
    Type: String
    Description: IAM policy json string with specified resources and json
    
Resources:
  Ec2IAMPolicy:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMPolicy
      ProvisioningArtifactName: 1.0.0
      ProvisionedProductName: !Sub "${ClusterName}-${Name}-policy-ec2-${AWS::Region}"
      ProvisioningParameters:
        - Key: PolicyNameSuffix
          Value: !Sub "${ClusterName}-${Name}-policy-ec2-${AWS::Region}"
        - Key: PolicyJSON
          Value: !Ref Ec2IAMPolicyJson
      Tags:
        - Key: doNotShutDown
          Value: "true"
  ElbIAMPolicy:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMPolicy
      ProvisioningArtifactName: 1.0.0
      ProvisionedProductName: !Sub "${ClusterName}-${Name}-policy-elb-${AWS::Region}"
      ProvisioningParameters:
        - Key: PolicyNameSuffix
          Value: !Sub "${ClusterName}-${Name}-policy-elb-${AWS::Region}"
        - Key: PolicyJSON
          Value: !Ref ElbIAMPolicyJson
      Tags:
        - Key: doNotShutDown
          Value: "true"  
  EKSServiceAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DependsOn:
      - Ec2IAMPolicy
      - ElbIAMPolicy
    Properties:
      ProductName: EKSServiceAccount
      ProvisioningArtifactName: 2.0.0
      ProvisionedProductName: !Sub uip-serviceaccount-${Name}-${AWS::Region}
      ProvisioningParameters:
        - Key: ClusterName
          Value: !Ref ClusterName
        - Key: Namespace
          Value: !Ref Namespace
        - Key: Name
          Value: !Sub ${Name}-${AWS::Region}
        - Key: PolicyARNs
          Value: !Join [ ",", [!Sub "${Ec2IAMPolicy.Outputs.PolicyARN}", !Sub "${ElbIAMPolicy.Outputs.PolicyARN}"] ]
        - Key: ServiceAccountDeployRole
          Value: !Sub /Team/EKS/Cluster/${ClusterName}/ServiceAccountDeployRole
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"