AWSTemplateFormatVersion: "2010-09-09"
Description: IAMPolicy and IAMRole to allow read write access to DynamoDB
Parameters:
  ClusterName: 
    Description: EKS cluster name
    Type: String
  Namespace:
    Description: EKS cluster namespace to create service account in.
    Type: String
    Default: kube-system
  Name:
    Description: EKS cluster create service account name.
    Type: String
  IAMPolicyJSON:
    Type: String
    Description: IAM policy json string with specified resources and json
  AdditonalPolicyArns:
    Type: String
    Description: IAM policy json string with specified resources and json
    Default: ""
Conditions:
  HasAdditonalPolicyArns: !Not [ !Equals [ !Ref AdditonalPolicyArns, "" ] ]  
Resources:
  IAMPolicy:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMPolicy
      ProvisioningArtifactName: 1.0.0
      ProvisionedProductName: !Sub "${ClusterName}-${Name}-policy-${AWS::Region}"
      ProvisioningParameters:
        - Key: PolicyNameSuffix
          Value: !Sub "${ClusterName}-${Name}-policy-${AWS::Region}"
        - Key: PolicyJSON
          Value: !Ref IAMPolicyJSON
      Tags:
        - Key: doNotShutDown
          Value: "true"
  EKSServiceAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DependsOn:
      - IAMPolicy
    Properties:
      ProductName: EKSServiceAccount
      ProvisioningArtifactName: 2.0.0
      ProvisionedProductName: !Sub uip-serviceaccount-${Name}-${AWS::Region}
      ProvisioningParameters:
        - Key: ClusterName
          Value: !Ref ClusterName
        - Key: Namespace
          Value: !Ref Namespace
        - Key: Name
          Value: !Sub ${Name}-${AWS::Region}
        - Key: PolicyARNs
          Value: !If [ HasAdditonalPolicyArns, !Join [ ",", [ !Sub "${IAMPolicy.Outputs.PolicyARN}", !Ref AdditonalPolicyArns ] ], !Sub "${IAMPolicy.Outputs.PolicyARN}" ] 
        - Key: ServiceAccountDeployRole
          Value: !Sub /Team/EKS/Cluster/${ClusterName}/ServiceAccountDeployRole
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"