apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.external_endpoint.prefix }}uip-services-public
  namespace: uip
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
{{- if .Values.external_endpoint.prefix }}
    alb.ingress.kubernetes.io/load-balancer-name: ext-uip-services-public-{{ .Values.cluster_name }}
{{- else }}
    alb.ingress.kubernetes.io/load-balancer-name: uip-services-public-{{ .Values.cluster_name }}
{{- end}}
{{- if .Values.https.enabled }}
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTPS\":443}]"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
{{- end }}
    alb.ingress.kubernetes.io/tags: Environment={{ .Values.environment }},Team=user-insights-platform,doNotShutDown=true,legal=USA
    alb.ingress.kubernetes.io/subnets: {{ .Values.subnets }}
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled={{ .Values.access_logs.enabled }},access_logs.s3.bucket={{ .Values.access_logs.s3bucket }},access_logs.s3.prefix=apis,deletion_protection.enabled=true
{{- if .Values.wafv2ACLArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.wafv2ACLArn }}
{{- end }}
    alb.ingress.kubernetes.io/target-group-attributes: "deregistration_delay.timeout_seconds={{ .Values.deregistration_delay.timeout_seconds }}, slow_start.duration_seconds={{ .Values.slow_start.duration_seconds }}"
spec:
  rules:
{{- if (eq .Values.environment "prod") }}
    - host: {{ .Values.external_endpoint.prefix }}uip.public.api.int.godaddy.com
{{- else if (eq .Values.environment "dev-private") }}
    - host: {{ .Values.external_endpoint.prefix }}uip-{{ .Values.dns_environment }}.public.api.int.dev-godaddy.com
{{- else }}
    - host: {{ .Values.external_endpoint.prefix }}uip.public.api.int.{{ .Values.dns_environment }}-godaddy.com
{{- end }}
      http:
        paths:
          # User (and Customer) Insights API
          - path: /v1/users/insights/mutate
            pathType: Exact
            backend:
              service:
                name: uip-ingest-api
                port:
                  number: 80
          - path: /docs/user-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: uip-ingest-api
                port:
                  number: 80

          # Subscription Insights API
          - path: /v1/subscriptions/insights/mutate
            pathType: Exact
            backend:
              service:
                name: subscription-ingest-api
                port:
                  number: 80
          - path: /docs/subscription-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: subscription-ingest-api
                port:
                  number: 80

          # User Aggregate Insights API
          - path: /v1/users/insights/aggregate/mutate
            pathType: Exact
            backend:
              service:
                name: users-aggregate-api
                port:
                  number: 80
          - path: /docs/user-aggregate-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: users-aggregate-api
                port:
                  number: 80


          # Product (Entitlement VA) Insights API
          - path: /v1/products/insights/mutate
            pathType: Exact
            backend:
              service:
                name: uip-product-ingest-api
                port:
                  number: 80
          - path: /docs/product-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: uip-product-ingest-api
                port:
                  number: 80

          # Business Insights API
          - path: /v1/businesses/insights/mutate
            pathType: Exact
            backend:
              service:
                name: business-ingest-api
                port:
                  number: 80
          - path: /docs/business-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: business-ingest-api
                port:
                  number: 80

          # Customer VA API
          - path: /v1/customer_va/insights/mutate
            pathType: Exact
            backend:
              service:
                name: customer-va-ingest-api
                port:
                  number: 80
          - path: /docs/customer-va-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: customer-va-ingest-api
                port:
                  number: 80

          # Seller VA API
          - path: /v1/seller_va/insights/mutate
            pathType: Exact
            backend:
              service:
                name: seller-va-ingest-api
                port:
                  number: 80
          - path: /docs/seller-va-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: seller-va-ingest-api
                port:
                  number: 80

          # [Old, in use, to depricate in future] GraphQL Router
          # all subgraphs are now routed via uip-graphql-router-api
          - path: /v1/users/insights/graphql
            pathType: Prefix
            backend:
              service:
                name: uip-graphql-router
                port:
                  number: 80

          # [New] GraphQL Router
          - path: /v1/insights/graphql
            pathType: Prefix
            backend:
              service:
                name: uip-graphql-router-api
                port:
                  number: 80

          # Insight Registry service
          - path: /v1/insight
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80
          - path: /v1/insights
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80
          - path: /v1/producers
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80
          - path: /v1/producer
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80
          - path: /docs/insight-registry
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80

          # Rule Catalog Service
          - path: /v1/rules
            pathType: Prefix
            backend:
              service:
                name: uip-rule-catalog-api
                port:
                  number: 80
          - path: /v1/rule/variables
            pathType: Prefix
            backend:
              service:
                name: uip-rule-catalog-api
                port:
                  number: 80
          - path: /docs/rule-catalog
            pathType: Prefix
            backend:
              service:
                name: uip-rule-catalog-api
                port:
                  number: 80

