template_path: simple-recordset.yaml

parameters:
  Endpoint: "keychain-us-east-1-api"
  Environment: {{ environment }}
  ALBDNSName: {{ var.keychain_useast1_alb_dns_name}}
  ALBHostedZoneId: {{ var.keychain_useast1_alb_hosted_zoneid }}