template_path: eks/addons/alb-service-account.yaml
parameters:
  ClusterName: "{{ cluster_name }}{{ resource_suffix }}"
  Namespace: kube-system{{ resource_suffix }}
  Name: {{ cluster_name }}-alb{{ resource_suffix }}
  Ec2IAMPolicyJson: !file_contents resources/iam-policies/alb/iam-policy-ec2.json
  ElbIAMPolicyJson: !file_contents resources/iam-policies/alb/iam-policy-elb.json
dependencies:
  - {{ environment }}/{{ region }}/{{ eks_folder_name }}/eks.yaml
  - {{ environment }}/{{ region }}/{{ eks_folder_name }}/eks-managed-nodegroup-arm64-b.yaml
  - {{ environment }}/{{ region }}/{{ eks_folder_name }}/eks-managed-nodegroup-x86.yaml
