template_path: eks/addons/service-account.yaml
parameters:
  ClusterName: "{{ cluster_name }}{{ resource_suffix }}"
  Namespace: kube-system{{ resource_suffix }}
  Name: {{ cluster_name }}-clstr-autoscaler{{ resource_suffix }}
  IAMPolicyJSON:  !file_contents resources/iam-policies/cluster-autoscaler/iam-policy.json
dependencies:
  - {{ environment }}/{{ region }}/{{ eks_folder_name }}/eks.yaml
  - {{ environment }}/{{ region }}/{{ eks_folder_name }}/eks-managed-nodegroup-arm64-b.yaml
