template_path: eks/addons/service-account.yaml
parameters:
  ClusterName: "{{ cluster_name }}{{ resource_suffix }}"
  Namespace: fluentbit{{ resource_suffix }}
  Name: {{ cluster_name }}-fluentbit{{ resource_suffix }}
  IAMPolicyJSON:  !file_contents resources/iam-policies/fluentbit/iam-policy.json
  AdditonalPolicyArns: arn:aws:iam::{{ account_id }}:policy/GD-AWS-KMS-USER
dependencies:
  - {{ environment }}/{{ region }}/{{ eks_folder_name }}/eks.yaml
  - {{ environment }}/{{ region }}/{{ eks_folder_name }}/eks-managed-nodegroup-arm64-b.yaml
