apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.external_endpoint.prefix }}uip-services
  namespace: uip
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
{{- if .Values.external_endpoint.prefix }}
    alb.ingress.kubernetes.io/load-balancer-name: ext-uip-services-{{ .Values.cluster_name }}
{{- else }}
    alb.ingress.kubernetes.io/load-balancer-name: uip-services-{{ .Values.cluster_name }}
{{- end}}
{{- if .Values.https.enabled }}
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTPS\":443}]"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
{{- end }}
    alb.ingress.kubernetes.io/tags: Environment={{ .Values.environment }},Team=user-insights-platform,doNotShutDown=true,legal=USA
    alb.ingress.kubernetes.io/subnets: {{ .Values.subnets }}
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled={{ .Values.access_logs.enabled }},access_logs.s3.bucket={{ .Values.access_logs.s3bucket }},access_logs.s3.prefix=apis,deletion_protection.enabled=true
{{- if .Values.wafv2ACLArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.wafv2ACLArn }}
{{- end }}
    alb.ingress.kubernetes.io/target-group-attributes: "deregistration_delay.timeout_seconds={{ .Values.deregistration_delay.timeout_seconds }}, slow_start.duration_seconds={{ .Values.slow_start.duration_seconds }}"
spec:
  rules:
{{- if (eq .Values.environment "prod") }}
    - host: {{ .Values.external_endpoint.prefix }}uip.api.int.godaddy.com
{{- else if (eq .Values.environment "dev-private") }}
    - host: {{ .Values.external_endpoint.prefix }}uip-{{ .Values.dns_environment }}.api.int.dev-godaddy.com
{{- else }}
    - host: {{ .Values.external_endpoint.prefix }}uip.api.int.{{ .Values.dns_environment }}-godaddy.com
{{- end }}
      http:
        paths:
          # User (and Customer) Insights API
          - path: /v1/users/insights/mutate
            pathType: Exact
            backend:
              service:
                name: uip-ingest-api
                port:
                  number: 80
          - path: /docs/user-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: uip-ingest-api
                port:
                  number: 80
          - path: /uip-ingest-api/health
            pathType: Exact
            backend:
              service:
                name: uip-ingest-api
                port:
                  number: 81
          - path: /uip-user-subgraph/health
            pathType: Exact
            backend:
              service:
                name: uip-user-subgraph
                port:
                  number: 81

          # Subscription Insights API
          - path: /v1/subscriptions/insights/mutate
            pathType: Exact
            backend:
              service:
                name: subscription-ingest-api
                port:
                  number: 80
          - path: /docs/subscription-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: subscription-ingest-api
                port:
                  number: 80
          - path: /subscription-ingest-api/health
            pathType: Exact
            backend:
              service:
                name: subscription-ingest-api
                port:
                  number: 81
          - path: /uip-subscription-subgraph/health
            pathType: Exact
            backend:
              service:
                name: uip-subscription-subgraph
                port:
                  number: 81

          # User Aggregate Insights API
          - path: /v1/users/insights/aggregate/mutate
            pathType: Exact
            backend:
              service:
                name: users-aggregate-api
                port:
                  number: 80
          - path: /docs/user-aggregate-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: users-aggregate-api
                port:
                  number: 80
          - path: /users-aggregate-api/health
            pathType: Exact
            backend:
              service:
                name: users-aggregate-api
                port:
                  number: 81

          # Product (Entitlement VA) Insights API
          - path: /v1/products/insights/mutate
            pathType: Exact
            backend:
              service:
                name: uip-product-ingest-api
                port:
                  number: 80
          - path: /docs/product-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: uip-product-ingest-api
                port:
                  number: 80
          - path: /uip-product-ingest-api/health
            pathType: Exact
            backend:
                service:
                  name: uip-product-ingest-api
                  port:
                    number: 81

          # Business Insights API
          - path: /v1/businesses/insights/mutate
            pathType: Exact
            backend:
              service:
                name: business-ingest-api
                port:
                  number: 80
          - path: /docs/business-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: business-ingest-api
                port:
                  number: 80
          - path: /business-ingest-api/health
            pathType: Exact
            backend:
              service:
                name: business-ingest-api
                port:
                  number: 81
          - path: /uip-business-subgraph/health
            pathType: Exact
            backend:
              service:
                name: uip-business-subgraph
                port:
                  number: 81

          # Customer VA API
          - path: /v1/customer_va/insights/mutate
            pathType: Exact
            backend:
              service:
                name: customer-va-ingest-api
                port:
                  number: 80
          - path: /docs/customer-va-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: customer-va-ingest-api
                port:
                  number: 80
          - path: /customer-va-ingest-api/health
            pathType: Exact
            backend:
              service:
                name: customer-va-ingest-api
                port:
                  number: 81
          - path: /uip-customer-va-subgraph/health
            pathType: Exact
            backend:
              service:
                name: uip-customer-va-subgraph
                port:
                  number: 81

          # Seller VA API
          - path: /v1/seller_va/insights/mutate
            pathType: Exact
            backend:
              service:
                name: seller-va-ingest-api
                port:
                  number: 80
          - path: /docs/seller-va-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: seller-va-ingest-api
                port:
                  number: 80
          - path: /seller-va-ingest-api/health
            pathType: Exact
            backend:
              service:
                name: seller-va-ingest-api
                port:
                  number: 81
          - path: /uip-seller-va-subgraph/health
            pathType: Exact
            backend:
              service:
                name: uip-seller-va-subgraph
                port:
                  number: 81

          # [Unused] Product Aggregate API
          - path: /v1/products/insights/aggregate/mutate
            pathType: Exact
            backend:
              service:
                name: product-aggregate-api
                port:
                  number: 80
          - path: /docs/product-aggregate-insights-ingest-api
            pathType: Prefix
            backend:
              service:
                name: product-aggregate-api
                port:
                  number: 80

          # [Old, in use, to depricate in future] GraphQL Router
          # all subgraphs are now routed via uip-graphql-router-api
          - path: /v1/users/insights/graphql
            pathType: Prefix
            backend:
              service:
                name: uip-graphql-router
                port:
                  number: 80
          - path: /healthcheck
            pathType: Exact
            backend:
              service:
                name: uip-graphql-router
                port:
                  number: 80

          # [New] GraphQL Router
          - path: /v1/insights/graphql
            pathType: Prefix
            backend:
              service:
                name: uip-graphql-router-api
                port:
                  number: 80
          - path: /v1/insights/graphql-router/healthcheck
            pathType: Exact
            backend:
              service:
                name: uip-graphql-router-api
                port:
                  number: 80

          # Insight Registry service
          - path: /v1/insight
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80
          - path: /v1/insights
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80
          - path: /v1/producers
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80
          - path: /v1/producer
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80
          - path: /docs/insight-registry
            pathType: Prefix
            backend:
              service:
                name: uip-insight-registry-api
                port:
                  number: 80

          # Rule Catalog Service
          - path: /v1/rules
            pathType: Prefix
            backend:
              service:
                name: uip-rule-catalog-api
                port:
                  number: 80
          - path: /v1/rule/variables
            pathType: Prefix
            backend:
              service:
                name: uip-rule-catalog-api
                port:
                  number: 80
          - path: /docs/rule-catalog
            pathType: Prefix
            backend:
              service:
                name: uip-rule-catalog-api
                port:
                  number: 80

          # [Unused] Customer Entitlement Service
          # all subgraphs are now routed via uip-graphql-router-api
          - path: /v1/entitlement/graphql
            pathType: Prefix
            backend:
              service:
                name: uip-customer-entitlement-subgraph
                port:
                  number: 80
          - path: /v1/entitlement/graphiql
            pathType: Prefix
            backend:
              service:
                name: uip-customer-entitlement-subgraph
                port:
                  number: 80
{{- if (eq .Values.environment "prod") }}
    - host: {{ .Values.external_endpoint.prefix }}asp.api.int.godaddy.com
{{- else if (eq .Values.environment "dev-private") }}
    - host: {{ .Values.external_endpoint.prefix }}asp-{{ .Values.dns_environment }}.api.int.dev-godaddy.com
{{- else }}
    - host: {{ .Values.external_endpoint.prefix }}asp.api.int.{{ .Values.dns_environment }}-godaddy.com
{{- end }}
      http:
        paths:
          # Segment Registry service
          - path: /docs/segment-registry
            pathType: Prefix
            backend:
              service:
                name: asp-segment-registry-api
                port:
                  number: 80
          - path: /v1/segments
            pathType: Prefix
            backend:
              service:
                name: asp-segment-registry-api
                port:
                  number: 80
          - path: /v1/producers
            pathType: Prefix
            backend:
              service:
                name: asp-segment-registry-api
                port:
                  number: 80

          # Customer Segments API
          - path: /v1/customers/segments/mutate
            pathType: Exact
            backend:
              service:
                name: asp-customer-ingest-api
                port:
                  number: 80
          - path: /docs/customer-segments-ingest-api
            pathType: Prefix
            backend:
              service:
                name: asp-customer-ingest-api
                port:
                  number: 80
#          uncomment after asp deployment
#          - path: /asp-customer-ingest-api/health
#            pathType: Exact
#            backend:
#              service:
#                name: asp-customer-ingest-api
#                port:
#                  number: 81

          # Segments GraphQL Router
          - path: /v1/segments/graphql
            pathType: Prefix
            backend:
              service:
                name: asp-graphql-router-api
                port:
                  number: 80
#          - path: /v1/segments/healthcheck
#            pathType: Exact
#            backend:
#              service:
#                name: asp-graphql-router-api
#                port:
#                  number: 80
