template_path: latency-recordset.yaml

parameters:
  Endpoint: "uip-public-api"
  AwsRegion: {{ region }}
  Environment: {{ environment }}
  ALBDNSName: {{ var.uip_public_alb_dns_name }}
  ALBHostedZoneId: {{ var.uip_public_alb_hosted_zoneid }}