template_path: simple-recordset.yaml

parameters:
  Endpoint: "asp-segments-us-west-2-api"
  Environment: {{ environment }}
  ALBDNSName: {{ var.asp_segments_uswest2_alb_dns_name}}
  ALBHostedZoneId: {{ var.asp_segments_uswest2_alb_hosted_zoneid }}
