template_path: latency-recordset.yaml

parameters:
  Endpoint: "asp-segments-api"
  AwsRegion: {{ region }}
  Environment: {{ environment }}
  ALBDNSName: {{ var.asp_segments_alb_dns_name }}
  ALBHostedZoneId: {{ var.asp_segments_alb_hosted_zoneid }}
