template_path: latency-recordset.yaml

parameters:
  Endpoint: "keychain-api"
  AwsRegion: {{ region }}
  Environment: {{ environment }}
  ALBDNSName: {{ var.keychain_alb_dns_name }}
  ALBHostedZoneId: {{ var.keychain_alb_hosted_zoneid }}