AWSTemplateFormatVersion: 2010-09-09
Description: Launch ECR Repository product from SC
Parameters:
  RepoName:
    Type: String
    Description: Name of ECR repo
  ECRMaxImageCount:
    Type: Number
    Description: Maximum number of the same image to keep (between 3 and 100)
Resources:
  InsightsPlatECRRepo:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: ECR
      ProvisioningArtifactName: 1.0.3
      ProvisionedProductName: !Ref RepoName
      ProvisioningParameters:
        - Key: ECRRepoName
          Value: !Ref RepoName
        - Key: ECRMaxImageCount
          Value: !Ref ECRMaxImageCount
      Tags:
        - Key: doNotShutDown
          Value: true