AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the EKS service account Service Catalog Product
Parameters:
  ClusterName:
    Description: EKS cluster name
    Type: String
  Namespace:
    Description: EKS cluster namespace to create service account in.
    Type: String
    Default: "kube-system"
  Name:
    Description: EKS cluster create service account name.
    Type: String
    Default: "ebs-csi-controller"

Resources:
  IAMPolicy:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMPolicy
      ProvisioningArtifactName: 1.0.0
      ProvisionedProductName: !Sub "${ClusterName}-${Name}-${AWS::Region}"
      ProvisioningParameters:
        - Key: PolicyNameSuffix
          Value: !Sub "${ClusterName}-${Name}-${AWS::Region}"
        - Key: PolicyJSON
          Value: !Sub |
              {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:CreateSnapshot",
                        "ec2:AttachVolume",
                        "ec2:DetachVolume",
                        "ec2:ModifyVolume",
                        "ec2:DescribeAvailabilityZones",
                        "ec2:DescribeInstances",
                        "ec2:DescribeSnapshots",
                        "ec2:DescribeTags",
                        "ec2:DescribeVolumes",
                        "ec2:DescribeVolumesModifications"
                      ],
                      "Resource": "*"
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:CreateTags"
                      ],
                      "Resource": [
                        "arn:aws:ec2:*:*:volume/*",
                        "arn:aws:ec2:*:*:snapshot/*"
                      ],
                      "Condition": {
                        "StringEquals": {
                          "ec2:CreateAction": [
                            "CreateVolume",
                            "CreateSnapshot"
                          ]
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:DeleteTags"
                      ],
                      "Resource": [
                        "arn:aws:ec2:*:*:volume/*",
                        "arn:aws:ec2:*:*:snapshot/*"
                      ]
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:CreateVolume"
                      ],
                      "Resource": "*",
                      "Condition": {
                        "StringLike": {
                          "aws:RequestTag/ebs.csi.aws.com/cluster": "true"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:CreateVolume"
                      ],
                      "Resource": "*",
                      "Condition": {
                        "StringLike": {
                          "aws:RequestTag/CSIVolumeName": "*"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:DeleteVolume"
                      ],
                      "Resource": "*",
                      "Condition": {
                        "StringLike": {
                          "ec2:ResourceTag/ebs.csi.aws.com/cluster": "true"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:DeleteVolume"
                      ],
                      "Resource": "*",
                      "Condition": {
                        "StringLike": {
                          "ec2:ResourceTag/CSIVolumeName": "*"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:DeleteVolume"
                      ],
                      "Resource": "*",
                      "Condition": {
                        "StringLike": {
                          "ec2:ResourceTag/kubernetes.io/created-for/pvc/name": "*"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:DeleteSnapshot"
                      ],
                      "Resource": "*",
                      "Condition": {
                        "StringLike": {
                          "ec2:ResourceTag/CSIVolumeSnapshotName": "*"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "ec2:DeleteSnapshot"
                      ],
                      "Resource": "*",
                      "Condition": {
                        "StringLike": {
                          "ec2:ResourceTag/ebs.csi.aws.com/cluster": "true"
                        }
                      }
                    }
                  ]
              }
      Tags:
        - Key: doNotShutDown
          Value: true
  EKSServiceAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: EKSServiceAccount
      ProvisioningArtifactName: 2.0.0
      ProvisionedProductName: !Sub ebs-csi-controller-${AWS::Region}-${ClusterName}
      ProvisioningParameters:
        - Key: ClusterName
          Value: !Ref ClusterName
        - Key: Namespace
          Value: !Ref Namespace
        - Key: Name
          Value: !Sub ${Name}-${AWS::Region}
        - Key: RoleNameSuffix
          Value: ""
        - Key: PolicyARNs
          Value: !Sub "${IAMPolicy.Outputs.PolicyARN}"
        - Key: ServiceAccountDeployRole
          Value: !Sub /Team/EKS/Cluster/${ClusterName}/ServiceAccountDeployRole
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: true
