AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the EKSManagedNodeGroup Service Catalog Product
Parameters:
  # Use default value or override in Stack Config
  ProductVersion:
    Type: String
    Default: 2.4.0
  KubernetesVersion:
    Type: String
    Default: "1.22"
  AmazonBase:
    Type: String
    Default: "amzn2"
  ClusterName:
    Type: String
  NodeGroupName:
    Type: String
    Default: example
  NodeInstanceType:
    Type: String
    Description: EC2 instance type for the Worker nodes
    Default: t4g.medium
  NodeGroupMinSize:
    Type: Number
    Description: Minimum Instances between 0 and 100
    Default: 1
  NodeGroupMaxSize:
    Type: Number
    Description: Maximum Instances between 0 and 100
    Default: 2
  NodeVolumeSize:
    Type: Number
    Description: Size of node volumes in GB between 20 and 1000
    Default: 20
  DXAppSubnetIds:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Description: SSM parameter referencing the Public Subnet IDs
    Default: /AdminParams/VPC/DXAPPSubnets
  CustomUserData:
    Type: String
    Description: (optional) User Data text to be appended to standard User Data script. Please insert as a single line.
    Default: "sleep 60"
  CapacityType:
    Type: String
    Description: The capacity type of your managed node group.
    Default: ON_DEMAND
    AllowedValues:
      - ON_DEMAND
      - SPOT
  UseARM:
    Type: String
    Description: Using ARM nodes
    Default: true
    AllowedValues:
      - false
      - true
  NodeVolumeIops:
    Type: Number
    Description: I/O operations per second for node volume (only used on io1 type volumes)
    Default: 500
    MinValue: 100
    MaxValue: 20000
  NodeVolumeType:
    Type: String
    Description: Node volume type
    Default: gp3
    AllowedValues:
      - standard
      - io1
      - gp2
      - gp3
Resources:
  LaunchConfigTrigger:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/Team/EKS/LaunchConfigTrigger/${ClusterName}-${NodeGroupName}-nodes"
      Type: String
      Value: random-trigger-value

  KubernetesWorkerNodes:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: EKSManagedNodeGroup
      ProvisioningArtifactName: !Ref ProductVersion
      ProvisionedProductName: !Sub eks-${NodeGroupName}-nodes
      ProvisioningParameters:
        # required parameters
        - Key: KubernetesVersion
          Value: !Ref KubernetesVersion
        - Key: ClusterName
          Value: !Ref ClusterName
        - Key: LaunchConfigTrigger
          Value: !Ref LaunchConfigTrigger
        - Key: AmazonBase
          Value: !Ref AmazonBase
        - Key: NodeGroupName
          Value: !Ref NodeGroupName
        - Key: VPCSubnetIds
          # Need to pass all List params as a String
          Value: !Join [ ",", !Ref DXAppSubnetIds ]
        - Key: NodeInstanceType
          Value: !Ref NodeInstanceType
        # common optional parameters
        - Key: NodeVolumeSize
          Value: !Ref NodeVolumeSize
        - Key: NodeVolumeType
          Value: !Ref NodeVolumeType
        - Key: NodeVolumeIops
          Value: !Ref NodeVolumeIops
        - Key: NodeEbsOptimized
          Value: "false"
        - Key: NodeGroupMinSize
          Value: !Ref NodeGroupMinSize
        - Key: NodeGroupMaxSize
          Value: !Ref NodeGroupMaxSize
        - Key: NodeGroupDesiredSize
          Value: !Ref NodeGroupMinSize
        - Key: EnableCloudWatchAgent
          Value: "true"
        - Key: BootstrapArguments
          Value: !Sub "--kubelet-extra-args --node-labels=node-group=${NodeGroupName}"
        - Key: CustomUserData
          Value: !Ref CustomUserData
        - Key: CapacityType
          Value: !Ref CapacityType
        - Key: UseARM
          Value: !Ref UseARM
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"
